#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

VENV_DIR="$SCRIPT_DIR/.test_venv"

cleanup() {
    echo "--- Cleaning up ---"
    if [[ -n "${SERVER_PID:-}" ]]; then
        kill "$SERVER_PID" 2>/dev/null || true
        wait "$SERVER_PID" 2>/dev/null || true
    fi
    rm -rf "$VENV_DIR"
}
trap cleanup EXIT

echo "=== Step 1: Build the wheel ==="
bazel build //python_package:grpc_services_wheel

WHEEL_PATH="$SCRIPT_DIR/$(bazel cquery --output=files //python_package:grpc_services_wheel 2>/dev/null)"
echo "Wheel built at: $WHEEL_PATH"

echo ""
echo "=== Step 2: Inspect wheel contents ==="
unzip -l "$WHEEL_PATH"

# Verify _pb2.pyi stubs are present
if unzip -l "$WHEEL_PATH" | grep -q '_pb2\.pyi'; then
    echo "OK: _pb2.pyi type stubs found in wheel"
else
    echo "FAIL: No _pb2.pyi type stubs found in wheel"
    exit 1
fi

# Verify _pb2_grpc.pyi stubs are present (generated by mypy-protobuf)
if unzip -l "$WHEEL_PATH" | grep -q '_pb2_grpc\.pyi'; then
    echo "OK: _pb2_grpc.pyi type stubs found in wheel"
else
    echo "FAIL: No _pb2_grpc.pyi type stubs found in wheel"
    exit 1
fi

# Verify py.typed marker is present (PEP 561)
if unzip -l "$WHEEL_PATH" | grep -q 'py\.typed'; then
    echo "OK: py.typed marker found in wheel"
else
    echo "FAIL: No py.typed marker found in wheel"
    exit 1
fi

echo ""
echo "=== Step 3: Set up test venv ==="
uv venv "$VENV_DIR"
uv pip install --python "$VENV_DIR/bin/python" "$WHEEL_PATH" grpcio protobuf

echo ""
echo "=== Step 4: Start echo server ==="
"$VENV_DIR/bin/python" "$SCRIPT_DIR/echo_server/server.py" --port 50051 &
SERVER_PID=$!
sleep 2

if ! kill -0 "$SERVER_PID" 2>/dev/null; then
    echo "FAIL: Server failed to start"
    exit 1
fi
echo "Server started (PID: $SERVER_PID)"

echo ""
echo "=== Step 5: Run echo client ==="
TEST_MESSAGE="Hello from integration test"
OUTPUT=$("$VENV_DIR/bin/python" "$SCRIPT_DIR/echo_client/client.py" "$TEST_MESSAGE")
echo "Client output:"
echo "$OUTPUT"

echo ""
echo "=== Step 6: Verify response ==="
if echo "$OUTPUT" | grep -q "$TEST_MESSAGE"; then
    echo "PASS: Response contains the sent message"
else
    echo "FAIL: Response does not contain the sent message"
    exit 1
fi

echo ""
echo "=== All tests passed ==="
